#!/usr/bin/env ruby

# Simple script for evaluating, formatting and/or
# freezing all `.dhall` files in a workspace

require 'find'
require 'open3'

def run(cmd, opts={})
	unless system(*cmd, opts)
		puts("FAILED: #{cmd.join(' ')}")
		exit(1)
	end
end

def main
	require 'optparse'
	actions = []
	options = {
		cache: false,
		all: false,
		fix_imports: true,
	}
	args = OptionParser.new do |p|
		p.banner = [
			"Usage: fix [OPTIONS] [PATH ...]",
			"",
			"If no paths are given, the current directory is used",
			"\n",
		].join("\n")

		action = -> (action, desc) do
			p.on("--#{action}", desc) { || actions << action }
		end

		action.call(:format, "Format files")
		action.call(:eval, "Test that all files evaluate")
		action.call(:freeze, "Freeze imports")
		action.call(:lint, "Canonicalize code")

		p.on('--no-fix-imports', "Skip hack for dhall-haskell#1672") do ||
			options[:fix_imports] = false
		end

		p.on('--explain', "") do ||
			options[:explain] = true
		end
		p.on('--cache', "(used with --freeze)") do ||
			options[:cache] = true
		end
		p.on('--all', "(used with --freeze)") do ||
			options[:all] = true
		end
	end.parse(ARGV)

	actions = [:eval, :format] if actions.empty?
	args << '.' if args.empty?

	args.each do |base|
		if File.directory?(base)
			paths = Find.find(base)
			file_filter = ->(path) { path.end_with?('.dhall') }
		else
			paths = [base]
			file_filter = ->(path) { true }
		end

		paths.each do |path|
			next if File.symlink?(path) || File.directory?(path)
			next unless file_filter.call(path)
			puts("[#{path}]")
			base_cmd = ['dhall', '--ascii']
			base_cmd << '--explain' if options[:explain]

			fix_imports = -> () do
				if options[:fix_imports]
					# workaround https://github.com/dhall-lang/dhall-haskell/issues/1672
					contents = File.read(path)
					fixed = contents.gsub(/(http[^ ]+ using) ([.\\\/~][^ ]+) (sha256:[^ $])/) do |x|
						match = Regexp.last_match
						"#{match[1]} (#{match[2]}) #{match[3]}"
					end
					if fixed != contents
						File.write(path, fixed)
					end
				end
			end

			if actions.include?(:freeze)
				cmd = base_cmd + ['freeze', '--inplace', path]
				cmd << '--cache' if options.fetch(:cache)
				cmd << '--all' if options.fetch(:all)
				run(cmd)
				fix_imports.call
			end

			if actions.include?(:eval)
				run(base_cmd + ['--plain', '--file', path], out: File::NULL)
			end

			if actions.include?(:format)
				run(base_cmd + ['format', '--inplace', path])
				fix_imports.call
			end

			if actions.include?(:lint)
				run(base_cmd + ['lint', '--inplace', path])
				fix_imports.call
			end
		end
	end
end

main
