#!/usr/bin/env bash
set -eu
#
# This script enables local imports using the following pattern:
#
# let Dependency =
#         (\(local : Bool) -> ../dependency/package.dhall ? local "import failed")
#           env:DHALL_LOCAL
#       ? https://(...)
#
# See the dhall-render readme for full details:
# https://github.com/timbertson/dhall-render#readme

SCOPES=()
while [ "$#" -gt 0 ]; do
	if [ "x$1" = "x-s" ]; then
		IFS=',' read -r -a SCOPES <<< "$(echo "$2" | tr '[:lower:]' '[:upper:]')"
		shift 2
	else
		break
	fi
done

export DHALL_LOCAL=True
for scope in ${SCOPES[@]+${SCOPES[@]}}; do
	eval "export DHALL_LOCAL_$scope=True"
done
exec "$@"
